### ISSUE TITLE
1.9.2 Support

### ISSUE THREAD

**Issue by pat** [evan/raspell#1]
Hi Evan

Just found out - via someone else logging an issue on thinking-sphinx-raspell - that raspell doesn't work on 1.9.2. Seems there's a few fixes around - I've given dmarkow's fork a go, and it works fine. Any chance of a new release of raspell to cover this?

Thanks!

Pat

**Comment by evan** [comment]
Fixed.

**Comment by pat** [comment]
Thanks :)
