### ISSUE TITLE
Setting a personal wordlist using set_option() is impossible

### ISSUE THREAD

**Issue by yorickpeterse** [evan/raspell#10]
Using `Aspell#set_option()` you should be able to specify a personal wordlist to use, this however doesn't appear to work unless this wordlist is set in `Aspell.new1`.  Assume you have the following wordlist:

```
personal_ws-1.1 en 28 utf-8
stylesheet
getter
erb
timestamp
checkboxes
Capybara's
isset
xhtml
csrf
https
strftime
nodoc
todo
procs
readline
namespace
backend
rb
frontend
rtl
textarea
mutex
github
boolean
reloader
regex
checkbox
login
```

And the following test:

``` ruby
require 'bacon'
require 'raspell'

Bacon.extend(Bacon::TapOutput)
Bacon.summary_on_exit

describe 'Aspell' do
  it 'Setting a personal wordlist using set_option()' do
    speller = Aspell.new('en')

    speller.set_option('personal', './.aspell.en.pws')

    speller.check('nodoc').should  == true
    speller.check('github').should == true
  end

  it 'Setting a personal wordlist using Aspell.new1()' do
    speller = Aspell.new1('lang' => 'en', 'personal' => './.aspell.en.pws')

    speller.check('nodoc').should  == true
    speller.check('github').should == true
  end
end
```

The resulting output of this test (assuming the wordlist is saved in `./.aspell.en.pws`) is this:

```
not ok 1 - Setting a personal wordlist using set_option(): FAILED
# Bacon::Error: false.==(true) failed
#   aspell.rb:13:in `block (2 levels) in <main>': Aspell - Setting a personal wordlist using set_option()
#   aspell.rb:8:in `block in <main>'
#   aspell.rb:7:in `<main>'
ok 2   - Setting a personal wordlist using Aspell.new1()
1..2
#2 tests, 3 assertions, 1 failures, 0 errors
```

In other words, setting the personal wordlist using `set_option` does not work.

**Comment by evan** [comment]
I don't personally use Raspell anymore so mostly I curate pull requests...patches welcome, if you can solve it.

**Comment by yorickpeterse** [comment]
My knowledge of writing Ruby extensions (and dealing with ugly looking C++ code) is very limited so I'm afraid I can't fix this issue myself.

**Comment by mariozaizar** [comment]
Please implement this.

**Comment by evan** [comment]
If you implement it I will accept a patch.

**Comment by evan** [comment]
Won't fix without patch.

**Comment by yorickpeterse** [comment]
@mariozaizar Due to the amount of bugs in this Gem, not being really Ruby-ish and not being maintained anymore I decided to create an FFI binding a while ago: https://github.com/YorickPeterse/ffi-aspell. It's an order of magnitude slower but it's a lot more stable than Raspell.

**Comment by evan** [comment]
Awesome, I will add a deprecation notice and redirect.
