### ISSUE TITLE
Segmentation Faul with numbers.

### ISSUE THREAD

**Issue by pbrunnader** [evan/raspell#12]
A Segmentation Faul is happening when a string which just contains digits (numbers) is happening. 

For example "06384894" or "1234". I don't know if it is a problem of raspell or the aspell library.

pbrunnader

**Comment by evan** [comment]
Works for me. 

irb(main):012:0> Aspell.new("en_US").check("06384894")
=> false

Anyway, you should be using ffi-aspell these days.
