### ISSUE TITLE
Problem with some UTF-8 characters

### ISSUE THREAD

**Issue by jisaac01** [evan/raspell#2]
I'm having trouble spellchecking certain words - for example words with smart quotes in them. 

raspell seems to swallow parts of the word, thinks correctly spelled words are incorrect, and I get back garbage.

See this example from irb:
ree-1.8.7-2010.02 > str = "what"; str << 226; str << 128; str << 153; str << "s"
 => "what’s" 
ree-1.8.7-2010.02 > a = Aspell.new('en');  a.list_misspelled([str])
 => ["what\342"] 

Here's another example from 1.9.1:
ruby-1.9.1-p429 > str = "what\342\200\231s"
 => "what’s" 
ruby-1.9.1-p429 > a.list_misspelled([str])
 => [] 
ruby-1.9.1-p429 > str = "whart\342\200\231s"
 => "whart’s" 
ruby-1.9.1-p429 > a.list_misspelled([str])
 => ["whart"] 
ruby-1.9.1-p429 > str.encoding.name
 => "UTF-8" 

When I a.dump_config, encoding is utf-8.

Not sure what's going on here, but it's preventing me from using this tool, as my users regularly paste in text from other programs with characters that confuse raspell.

**Comment by jisaac01** [comment]
This looks to be ultimately an issue with Aspell. 

Inside raspell's call to aspell_list_misspelled, you iterate over aspell_document_checker_next_misspelling(checker) tokens. However, the token.length returned is incorrect when these kinds of UTF-8 characters are passed in.

Looks like the next version of Aspell (0.60.7) may address these issues, although I have not tried.

**Comment by evan** [comment]
Hmm. Should we be calculating token length ourselves then? Or just wait for 0.60.7 to drop?

**Comment by jisaac01** [comment]
I worked around this issue by iterating over my list of words and calling check on each one, replacing any smart quotes beforehand.  Since check returns true or false, I simply reject any words from my original array that are spelled correctly, and the client gets back a list of words with the original smart quotes. This didn't seem to be any slower for the smallish documents I am using it for. So I have a workaround :)
